### ISSUE TITLE
Document the bower package is "quick-ngrepeat" not "quick-ng-repeat"

### ISSUE THREAD

**Issue by AshCoolman** [allaud/quick-ng-repeat#25]
There is an old fork which is in bower as "quick-ng-repeat" which caused me a bit of confusion:
If the readme could have a section like this, it would of saved me some grief:

## Installation
```
bower i quick-ngrepeat --save
```

**Comment by allaud** [comment]
@AshCoolman what about a PR?

**Comment by AshCoolman** [comment]
will do (in my lunch break)
