### ISSUE TITLE
bump bower version

### ISSUE THREAD

**Issue by mikey0000** [allaud/quick-ng-repeat#27]
I had an issue with quick-ng-repeat only to find you've fixed it upstream  (which is great well done) however bower won't update because you never update the version number.

Edit: I noticed the bower version is on a different account???

Pretty please!

**Comment by allaud** [comment]
We now have a bower instructions in readme. Have you noticed?

**Comment by mikey0000** [comment]
thanks, no I did not as I originally installed the one from the old account, thanks will point at that instead.
